ALTER TABLE items
    ADD COLUMN IF NOT EXISTS page_count INTEGER,
    ADD COLUMN IF NOT EXISTS isbn_13 TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS isbn_10 TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
