ALTER TABLE items
    ADD COLUMN IF NOT EXISTS platform TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS age_group TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS player_count TEXT NOT NULL DEFAULT '';
